apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "product-dataproduct"
  # namespace: broda-group-software
  title: "Product Data Product 01"
  description: "Broda Group Software sample product data product"
  # labels:
  # annotations:
  tags: ["account", "party", "product", "transaction", "data-product"]
  links:
    - url: https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-license.yaml
      title: Documentation
    - url: https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-license.yaml
      title: Getting Started Guide
    - url: https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-license.yaml
      title: Sandboxes
spec:
  type: data-product
  lifecycle: "experimental"
  owner: "user:eric.broda"
  system: "customer-analytics"
  subcomponentOf: "parent-1"
  providesApis: ["somePublishedAPI"]
  consumesApis: ["someConsumedAPI"]
  dependsOn: ["component:account-dataproduct", "component:party-dataproduct", "component:transaction-dataproduct"]
